name: chat_client
description: Starting point for a Serverpod client.

publish_to: none

resolution: workspace

environment:
  sdk: '^3.8.0'

dependencies:
  serverpod_auth_idp_client: 3.4.5
  serverpod_client: 3.4.5
