/* Hand-written Serverpod-compatible model classes for the stories feature.
 * Normally these would be generated by `serverpod generate` from the YAML
 * definitions in lib/src/stories/story.yaml and story_view_record.yaml.
 *
 * Until code-generation is run, these classes provide the full
 * TableRow / ProtocolSerialization contract so the rest of the server
 * (endpoint, migration, tests) can compile and function.
 */

import 'package:serverpod/serverpod.dart';

// ── Story ────────────────────────────────────────────────────────────────────

/// Ephemeral story / post (encrypted content; 24 h TTL).
///
/// The server stores only ciphertext; decryption happens exclusively on
/// client devices via the E2EE module.
class Story implements TableRow<UuidValue>, ProtocolSerialization {
  Story._({
    required this.id,
    required this.authorAuthUserId,
    required this.mediaType,
    required this.encryptedPayload,
    required this.nonce,
    this.thumbnailCiphertext,
    String? privacy,
    this.selectedViewerIds,
    DateTime? expiresAt,
    DateTime? createdAt,
  })  : privacy = privacy ?? 'all_contacts',
        expiresAt = expiresAt ?? DateTime.now().toUtc().add(const Duration(hours: 24)),
        createdAt = createdAt ?? DateTime.now().toUtc();

  factory Story({
    required UuidValue id,
    required UuidValue authorAuthUserId,
    required String mediaType,
    required String encryptedPayload,
    required String nonce,
    String? thumbnailCiphertext,
    String? privacy,
    String? selectedViewerIds,
    DateTime? expiresAt,
    DateTime? createdAt,
  }) = _StoryImpl;

  factory Story.fromJson(Map<String, dynamic> jsonSerialization) {
    return Story(
      id: UuidValueJsonExtension.fromJson(jsonSerialization['id']),
      authorAuthUserId: UuidValueJsonExtension.fromJson(
        jsonSerialization['authorAuthUserId'],
      ),
      mediaType: jsonSerialization['mediaType'] as String,
      encryptedPayload: jsonSerialization['encryptedPayload'] as String,
      nonce: jsonSerialization['nonce'] as String,
      thumbnailCiphertext:
          jsonSerialization['thumbnailCiphertext'] as String?,
      privacy: jsonSerialization['privacy'] as String? ?? 'all_contacts',
      selectedViewerIds:
          jsonSerialization['selectedViewerIds'] as String?,
      expiresAt: jsonSerialization['expiresAt'] == null
          ? null
          : DateTimeJsonExtension.fromJson(jsonSerialization['expiresAt']),
      createdAt: jsonSerialization['createdAt'] == null
          ? null
          : DateTimeJsonExtension.fromJson(jsonSerialization['createdAt']),
    );
  }

  static final t = StoryTable();

  @override
  UuidValue id;

  UuidValue authorAuthUserId;

  String mediaType;

  String encryptedPayload;

  String nonce;

  String? thumbnailCiphertext;

  String privacy;

  String? selectedViewerIds;

  DateTime expiresAt;

  DateTime createdAt;

  @override
  Table<UuidValue> get table => t;

  @override
  Map<String, dynamic> toJson() {
    return {
      '__className__': 'Story',
      'id': id.toJson(),
      'authorAuthUserId': authorAuthUserId.toJson(),
      'mediaType': mediaType,
      'encryptedPayload': encryptedPayload,
      'nonce': nonce,
      if (thumbnailCiphertext != null)
        'thumbnailCiphertext': thumbnailCiphertext,
      'privacy': privacy,
      if (selectedViewerIds != null) 'selectedViewerIds': selectedViewerIds,
      'expiresAt': expiresAt.toJson(),
      'createdAt': createdAt.toJson(),
    };
  }

  @override
  Map<String, dynamic> toJsonForProtocol() => toJson();

  @override
  String toString() => SerializationManager.encode(this);
}

class _Undefined {}

class _StoryImpl extends Story {
  _StoryImpl({
    required super.id,
    required super.authorAuthUserId,
    required super.mediaType,
    required super.encryptedPayload,
    required super.nonce,
    super.thumbnailCiphertext,
    super.privacy,
    super.selectedViewerIds,
    super.expiresAt,
    super.createdAt,
  }) : super._();
}

class StoryTable extends Table<UuidValue> {
  StoryTable({super.tableRelation}) : super(tableName: 'story') {
    authorAuthUserId = ColumnUuid('authorAuthUserId', this);
    mediaType = ColumnString('mediaType', this);
    encryptedPayload = ColumnString('encryptedPayload', this);
    nonce = ColumnString('nonce', this);
    thumbnailCiphertext = ColumnString('thumbnailCiphertext', this);
    privacy = ColumnString('privacy', this);
    selectedViewerIds = ColumnString('selectedViewerIds', this);
    expiresAt = ColumnDateTime('expiresAt', this);
    createdAt = ColumnDateTime('createdAt', this);
  }

  late final ColumnUuid authorAuthUserId;
  late final ColumnString mediaType;
  late final ColumnString encryptedPayload;
  late final ColumnString nonce;
  late final ColumnString thumbnailCiphertext;
  late final ColumnString privacy;
  late final ColumnString selectedViewerIds;
  late final ColumnDateTime expiresAt;
  late final ColumnDateTime createdAt;

  @override
  List<Column> get columns => [
        id,
        authorAuthUserId,
        mediaType,
        encryptedPayload,
        nonce,
        thumbnailCiphertext,
        privacy,
        selectedViewerIds,
        expiresAt,
        createdAt,
      ];
}

// ── StoryViewRecord ──────────────────────────────────────────────────────────

class StoryViewRecord implements TableRow<UuidValue?>, ProtocolSerialization {
  StoryViewRecord._({
    this.id,
    required this.storyId,
    required this.viewerAuthUserId,
    DateTime? viewedAt,
  }) : viewedAt = viewedAt ?? DateTime.now().toUtc();

  factory StoryViewRecord({
    UuidValue? id,
    required UuidValue storyId,
    required UuidValue viewerAuthUserId,
    DateTime? viewedAt,
  }) = _StoryViewRecordImpl;

  factory StoryViewRecord.fromJson(Map<String, dynamic> jsonSerialization) {
    return StoryViewRecord(
      id: jsonSerialization['id'] == null
          ? null
          : UuidValueJsonExtension.fromJson(jsonSerialization['id']),
      storyId: UuidValueJsonExtension.fromJson(jsonSerialization['storyId']),
      viewerAuthUserId: UuidValueJsonExtension.fromJson(
        jsonSerialization['viewerAuthUserId'],
      ),
      viewedAt: jsonSerialization['viewedAt'] == null
          ? null
          : DateTimeJsonExtension.fromJson(jsonSerialization['viewedAt']),
    );
  }

  static final t = StoryViewRecordTable();

  @override
  UuidValue? id;

  UuidValue storyId;

  UuidValue viewerAuthUserId;

  DateTime viewedAt;

  @override
  Table<UuidValue?> get table => t;

  @override
  Map<String, dynamic> toJson() {
    return {
      '__className__': 'StoryViewRecord',
      if (id != null) 'id': id?.toJson(),
      'storyId': storyId.toJson(),
      'viewerAuthUserId': viewerAuthUserId.toJson(),
      'viewedAt': viewedAt.toJson(),
    };
  }

  @override
  Map<String, dynamic> toJsonForProtocol() => toJson();

  @override
  String toString() => SerializationManager.encode(this);
}

class _StoryViewRecordImpl extends StoryViewRecord {
  _StoryViewRecordImpl({
    super.id,
    required super.storyId,
    required super.viewerAuthUserId,
    super.viewedAt,
  }) : super._();
}

class StoryViewRecordTable extends Table<UuidValue?> {
  StoryViewRecordTable({super.tableRelation})
      : super(tableName: 'story_view') {
    storyId = ColumnUuid('storyId', this);
    viewerAuthUserId = ColumnUuid('viewerAuthUserId', this);
    viewedAt = ColumnDateTime('viewedAt', this);
  }

  late final ColumnUuid storyId;
  late final ColumnUuid viewerAuthUserId;
  late final ColumnDateTime viewedAt;

  @override
  List<Column> get columns => [id, storyId, viewerAuthUserId, viewedAt];
}
